# Make some basic iControlRest calls to setup network elements on BIG-IP
# A more polished implementation might include custom ansible modules for these
# steps. 

# Instead we use iControlRest (nearly) directly.  We wrap the iCR calls to 
# provide a bit of idempotence.  See library/bigip_config
---

# ----------------------------------------------------------------------
# License BIGIP 
# ----------------------------------------------------------------------


# Example of setting license for license.f5.com in 12.0.0+ w/ REST
# - name: License BIG-IP for BYOL
#   delegate_to: localhost
#   bigip_config:
#     state=present
#     host={{ inventory_hostname }}
#     user={{ bigip_rest_user }}
#     password={{ bigip_rest_pass }}
#     payload='{"command":"install", "registrationKey":"{{RegKey}}"}'
#     collection_path='mgmt/tm/sys/license'
#

- name: License the bigip using Ansible Module
  bigip_license: connection={{ license_connection }}
                 hostname={{ inventory_hostname }}
                 key={{ RegKey }}
                 license_server={{ license_server }}
                 username={{ bigip_rest_user }}
                 password={{ bigip_rest_pass }}
                 wsdl=/Users/applebaum/shared/git/my-repos/ansible/aws-deployments/roles/bigip_license/files/authem.f5net.com-f5wsdl-w-https.xml
  delegate_to: localhost

#- name: License the bigip using old script
#  script: ../library/bigip_license_bigsuds.py -b {{inventory_hostname}} -u \'{{bigip_rest_user}}\' -p \'{{bigip_rest_pass}}\' -r \'{{RegKey}}\' -s {{license_server}}
#  delegate_to: localhost


