---
# tasks file for bigip
#  All tmsh commands use "executable: bash" to ensure that ssh drops out of tmsh,
#    otherwise tmsh will puke when ansible tries to drop into /bin/sh
# - name: run bash
#   raw: bash

- name: Check for user 
  raw: list auth user {{ bigip_rest_user }}
  register: list_user 
  ignore_errors: True

  #Conditionally create a user if not found
- name: create a user for rest 
  raw: create auth user {{ bigip_rest_user }} password '{{ bigip_rest_pass }}' partition-access add { all-partitions { role admin } } shell tmsh  
  when: list_user.stdout | search("was not found")
  ignore_errors: True



