---
# make a directory for this new deployment
- file: path="~/vars/f5aws/env/{{ env_name }}" state="directory"
- file: path="~/vars/f5aws/env/{{ env_name }}/inventory" state="directory"
- file: path="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars" state="directory"

- file: path="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/apphosts" state="touch"
- file: path="~/vars/f5aws/env/{{ env_name }}/inventory/host_vars" state="directory"

# create some files for the roles/hosts we know we need
#- template: src="host_vars_localhosts.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/localhosts"

# create some files for the roles/hosts we know we need
- template: src="group_vars_managers.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/managers"

# add some group vars for the bigips we will provision
- template: src="group_vars_bigip.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/bigips"

# add some group vars for the gtms we will provision
- template: src="group_vars_gtm.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/gtms"



# add a template to be used when we deploy the amazon infrstructure (vpc, subnets, bigips, etcs)
- template: src="{{ deployment_model }}-hosts.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/hosts"

