---
# Create the directory structure for this deployment
- file: path="~/vars/f5aws/env/{{ env_name }}" state="directory"
- file: path="~/vars/f5aws/env/{{ env_name }}/inventory" state="directory"
- file: path="~/vars/f5aws/env/{{ env_name }}/inventory/host_vars" state="directory"
- file: path="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars" state="directory"

# Creating group_vars files for 'localhosts'

- file: path="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/apphosts" state="touch"
- template: src="group_vars_localhosts.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/localhosts"

# Adding group vars for dynamic groups that will be provisioned
- template: src="group_vars_clients.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/clients"
- template: src="group_vars_apphosts.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/apphosts"
- template: src="group_vars_bigips.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/bigips"
- template: src="group_vars_gtms.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/gtms"

# Adding hosts file from template
- template: src="{{ deployment_model }}.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/hosts"
