---
- name: Setting LTM to minimum
  delegate_to: localhost
  bigip_config:
    state=present
    host={{ ansible_ssh_host }}
    user={{ bigip_rest_user }}
    password={{ bigip_rest_password }}
    payload='{"level":"minimum"}'
    collection_path='mgmt/tm/sys/provision/ltm'

- name: Provision GTM
  delegate_to: localhost
  bigip_config:
    state=present
    host={{ ansible_ssh_host }}
    user={{ bigip_rest_user }}
    password={{ bigip_rest_password }}
    payload='{"level":"nominal"}'
    collection_path='mgmt/tm/sys/provision/gtm'

- name: Pausing for module provisioning to complete
  pause: seconds=30
  tags:
      - pause
