---  
- name: Create subnets in all availability zones
  cloudformation:
    stack_name="{{ env_name }}-{{ inventory_hostname }}"
    state=present
    region="{{ region }}"
    template={{ install_path }}/roles/infra/files/az.json
  args:
    tags:
      Environment: "{{ env_name }}"
      InventoryHostname: "{{ inventory_hostname }}"
    template_parameters:
      vpc: "{{ vpc_id }}"
      internetGateway: "{{ internet_gateway_id }}"
      availabilityZone: "{{ availability_zone }}"
      managementSubnetCidr: "{{ management_cidr }}"
      privateSubnetCidr: "{{ private_cidr }}"
      publicSubnetCidr: "{{ public_cidr }}"
      applicationSubnetCidr: "{{ application_cidr }}"
  register: az_deploy_results

- debug: var=az_deploy_results

- name: create a file in which to persist results
  template: src='host-managers.j2' dest=~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/{{zone_id}}-az-managers

- copy: content="{{ az_deploy_results | to_yaml }}" dest=~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.yml
- copy: content="{{ az_deploy_results['stack_outputs'] | to_json }}" dest=~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.json
