---
- name: Deleting BIG-IP cfn stack(s)
  action: cloudformation
    stack_name="{{ env_name }}-{{ inventory_hostname }}"
    state=absent
    region="{{ region }}"
    template={{ install_path }}/roles/infra/files/bigip.json
  register: bigip_teardown_results
  ignore_errors: yes

- copy: content="{{ bigip_teardown_results | to_yaml }}" dest=~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.yml

