---
# Deploy the Client host AMI via CFT

- hosts: zone1-clienthost-manager
  gather_facts: no
  tasks:
    - name: deploy client host 
      include: "{{ install_path }}/roles/infra/tasks/deploy_client.yml"


