---
# Deploy the docker host AMIs via CFT
- hosts: apphosts
  gather_facts: no
  vars:
     ansible_connection: local
     ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - name: deploy app host cft 
      include: "{{ install_path }}/roles/infra/tasks/deploy_apphost_cft.yml"
      delegate_to: localhost
