---

- hosts: apphosts
  gather_facts: False
  vars_files:
   - [ "~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.yml" ]
  tasks: 
#  
#     - name: Add CFT variables to host
#       set_fact: item.key  = item.value
#       with_dict: hostvars[inventory_hostname].stack_outputs
# 
    - name: Add CFT output variables to host from persisted results from previous playbooks 
      set_fact:
        ansible_ssh_host={{ hostvars[inventory_hostname].stack_outputs.WebServerInstancePublicIp }}
        WebServerInstancePublicIp={{ hostvars[inventory_hostname].stack_outputs.WebServerInstancePublicIp }}
        WebServerInstancePrivateIp={{ hostvars[inventory_hostname].stack_outputs.WebServerInstancePrivateIp }}



# Wait for hosts to become ready
- hosts: apphosts
  gather_facts: False
  sudo: false
  tasks:

    - name:  Wait for ssh port to open
      local_action: wait_for host={{ ansible_ssh_host }} search_regex=OpenSSH delay=10 port=22

# Create docker containers on the application hosts
- hosts: apphosts
  gather_facts: False
  vars:
    ansible_sudo: True
  roles:
    - docker_base
    - app

# New set of tasks without sudo
- hosts: apphosts
  gather_facts: False
  tasks:
    - name: Store docker containers from jinja template
      local_action: template src=../roles/app/templates/docker_containers.cfg.j2  dest=~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}_docker_containers.yml


