# Removes the inventory for a deployed an environment

---
- hosts: localhosts
  gather_facts: False
  tasks:
    - name: deploy vpc
      include: "{{ install_path }}/roles/inventory_manager/tasks/teardown.yml"