---
- hosts: clients
  gather_facts: no
  vars_files:
   - [ "~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.yml" ]
  tasks:
    - name: Add CFT output variables to host from persisted results from previous playbooks
      set_fact:
        ansible_ssh_host={{ hostvars[inventory_hostname].stack_outputs.ClientInstancePublicIp }}
        ClientInstancePublicIp={{ hostvars[inventory_hostname].stack_outputs.ClientInstancePublicIp }}
        ClientInstancePrivateIp={{ hostvars[inventory_hostname].stack_outputs.ClientInstancePrivateIp }}

# Kill Jmeter test clients
- hosts: clients
  gather_facts: no
  tasks:

    - name: Kill Jmeter 
      #shell: kill `ps -ef | egrep jmeter | egrep -v egrep | awk '{print $2}'`
      shell: killall java

   
